---
- name: Automatyzacja Windows Server – Magazyn i Udział
  hosts: winsrv
  gather_facts: no
  tasks:

    - name: Utwórz pulę dyskową StoragePool_Napiorkowski
      ansible.windows.win_storagepool:
        name: StoragePool_Napiorkowski
        physical_disks:
          - 1
          - 2
          - 3
          - 4
        state: present
        auto_configure_tiering: yes

    - name: Utwórz wirtualny dysk VirtualDisk_Napiorkowski
      ansible.windows.win_virtualdisk:
        name: VirtualDisk_Napiorkowski
        storage_pool: StoragePool_Napiorkowski
        size: maximum
        resiliency_setting_name: Mirror
        state: present

    - name: Sformatuj dysk ReFS i przypisz literę F
      ansible.windows.win_volume:
        disk_number: 0
        file_system: ReFS
        drive_letter: F
        state: present

    - name: Utwórz grupę Kierownicy_Napiorkowski
      ansible.windows.win_group:
        name: Kierownicy_Napiorkowski
        state: present

    - name: Utwórz użytkownika Marek Romanek
      ansible.windows.win_user:
        name: "Marek Romanek"
        password: "Zaq12wsx"
        groups:
          - Kierownicy_Napiorkowski
        state: present

    - name: Utwórz użytkownika Jacek Gula
      ansible.windows.win_user:
        name: "Jacek Gula"
        password: "Zaq12wsx"
        groups:
          - Kierownicy_Napiorkowski
        state: present

    - name: Utwórz katalog Projekty na dysku F
      ansible.windows.win_file:
        path: "F:\Projekty"
        state: directory

    - name: Udostępnij katalog Projekty_Napiorkowski
      ansible.windows.win_share:
        name: "Projekty_Napiorkowski"
        path: "F:\Projekty"
        full_access:
          - "Kierownicy_Napiorkowski"
          - "Administrator"
        state: present

    - name: Zainstaluj 7zip
      ansible.windows.win_chocolatey:
        name: 7zip
        state: present

    - name: Zainstaluj dig
      ansible.windows.win_chocolatey:
        name: bind-toolsonly
        state: present

    - name: Zainstaluj Firefox
      ansible.windows.win_chocolatey:
        name: firefox
        state: present
