---
- name: Backup AdGuard Home
  hosts: agh
  become: true
  vars:
    adguard_data_dir: "/adguardhome"
    backup_dir_local: "/home/user/Ansible_Mateusz/adguard_backup"
    backup_dir_ansible: "/root/Ansible_Mateusz/adguard_backup"
    date: "{{ lookup('pipe', 'date +%Y-%m-%d_%H-%M-%S') }}"
    backup_file: "{{ backup_dir_local }}/adguard_backup_{{ date }}.tar.gz"

  tasks:
    - name: Ensure backup directory exists on AGH
      file:
        path: "{{ backup_dir_local }}"
        state: directory
        mode: '0755'

    - name: Create compressed backup of AdGuard Home data
      archive:
        path: "{{ adguard_data_dir }}"
        dest: "{{ backup_file }}"
        format: gz

    - name: Ensure backup directory exists on Ansible host
      delegate_to: localhost
      file:
        path: "{{ backup_dir_ansible }}"
        state: directory
        mode: '0755'

    - name: Copy backup to Ansible host
      fetch:
        src: "{{ backup_file }}"
        dest: "{{ backup_dir_ansible }}/"
        flat: yes

    - name: List backups on Ansible host
      delegate_to: localhost
      shell: ls -lh "{{ backup_dir_ansible }}"
      register: backup_list

    - name: Show available backups
      debug:
        msg: "{{ backup_list.stdout_lines }}"
