---
- name: Backup AdGuard Home
  hosts: agh
  become: true

  vars:
    adguard_data_dir: /adguardhome
    backup_dir_agh: /home/user/adguard_backup

  tasks:

    - name: Create backup directory on AGH
      ansible.builtin.file:
        path: "{{ backup_dir_agh }}"
        state: directory
        owner: user
        mode: '0755'

    - name: Create AdGuard Home backup archive
      ansible.builtin.archive:
        path: "{{ adguard_data_dir }}"
        dest: "{{ backup_dir_agh }}/adguard_backup.tar.gz"
        format: gz

    - name: Fetch backup to Ansible host (Semaphore container)
      ansible.builtin.fetch:
        src: "{{ backup_dir_agh }}/adguard_backup.tar.gz"
        dest: "./adguard_backups/"
        flat: yes
